### ISSUE TITLE
I get this issue when trying to run the bot, I don't know if you will answer this but asking just in case.

### ISSUE THREAD

**Issue by amoraschi** [MorganAnkan/mineflayer-notebot#2]
**When I run: node index.js (I am in the correct directory), I get**

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**And when I change in the index.js the version from 1.15.2 to 1.16.1 I get:**

(notebot) logged in!
E:\Test\Test\mineflayer-notebot-master\node_modules\prismarine-physics\index.js:599
    const boots = bot.inventory.slots[8]
                                ^

TypeError: Cannot read property 'slots' of undefined
    at new PlayerState (E:\Test\Test\mineflayer-notebot-master\node_modules\prismarine-physics\index.js:599:33)
    at Timeout.doPhysics [as _onTimeout] (E:\Test\Test\mineflayer-notebot-master\node_modules\mineflayer\lib\plugins\physics.js:61:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**I don't know what to do, help!**

**Thanks in advance**

@MorganAnkan @TheCosmic04 @BlueBurgersTDD

**Comment by amoraschi** [comment]
Nevermind, I just deleted the line that was giving the error from the index.js of \prismarine-physics\ and now it works.

**Comment by MorganAnkan** [comment]
ah nice sorry for no response though
